# If you have questions regarding the website, please contact Ziqi Kang: ziqi.kang@helsinki.fi

baseURL: http://cytodata.org/
languageCode: en-us
title: CytoData Society
theme: ["PaperMod_modified"]

menu:
  main:
    - identifier: 2025
      name: Cytodata 2025
      url: /symposia/2025/
      weight: 5
    - identifier: symposia
      name: Symposia
      url: /symposia
      weight: 10
    - identifier: resources
      name: Resources
      url: /resources
      weight: 20
    - identifier: board
      name: Board
      url: /board
      weight: 30
    - identifier: society
      name: Society
      url: /society
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact
      weight: 50

params:
  defaultTheme: auto
  ShowWordCount: true
  ShowShareButtons: true
  env: production
  title: CytoData
  description: "CytoData Society for biological image profiling"
  profileMode:
    enabled: true
    title: "We are CytoData society!" # optional default will be site title
    subtitle: "The **CytoData society (CytoDS)** builds and maintains an active community around **image-based profiling of biological phenotypes** induced by genetic, chemical or other perturbations of biological systems."
    imageUrl: "./main_files/cytodata-banner-new.png" # optional
    imageWidth: 320 # custom size
    imageHeight: 300 # custom size
    buttons:
      - name: Sign up for news
        url: "/contact"
       
    

  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/cytodata"
    - name: "X"
      url: "https://twitter.com/CytoData"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/company/cytodata"
    - name: "Email"
      url: "cytodata.info@gmail.com"

cover:
    linkFullImages: true
    # Hide everywhere but not in structured data
    hidden: false
    # Hide in list view
    hiddenInList: false
    hiddenInSingle: true

markup:
  tableOfContents:
    # Without this, Hugo ToC doesn't show h4 and higher
    # https://github.com/alex-shpak/hugo-book/issues/52
    endLevel: 6
  
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    # false means use external CSS file
    noClasses: false
    noHl: false
    # style: monokai
    tabWidth: 4

