[build]
  publish = "public"

[params]
	social = true

[build.environment]
  HUGO_VERSION = "0.145.0"

[context.production]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"
